name: Dependabot PR Check
on: pull_request

jobs:
  check-dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    needs: Call-Tests-Workflow
    steps:
      - run: echo "PR created by Dependabot"

  Call-Tests-Workflow:
    uses: ./.github/workflows/tests.yaml
